movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('recommended/', views.recommended, name='recommended'),
    path('recommended2/', views.recommended2, name='recommended2'),
    path('mvti/', views.mvti, name='mvti'),
]

pjt09/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

movies/models.py
from django.db import models

class Genre(models.Model):
    name = models.CharField(max_length=50)

class Movie(models.Model):
    title = models.CharField(max_length=100)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    overview = models.TextField()
    poster_path = models.CharField(max_length=200)
    genres = models.ManyToManyField(Genre)

movies/forms.py
from django import forms

# Create your forms here.

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from .models import Movie
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from random import random, sample

# Create your views here.
@require_GET
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)


@require_GET
def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)

@login_required
@require_GET
def recommended(request):
    today_month = datetime.today().month
    movies = Movie.objects.filter(release_date__month=today_month)
    from_now = dict()
    for movie in movies:
        from_now[movie.pk] = datetime.today().year-movie.release_date.year
    context = {
        'today_month': today_month,
        'movies': movies,
        'from_now': from_now,
    }
    return render(request, 'movies/recommended.html', context)


@login_required
@require_GET
def recommended2(request):
    return render(request, 'movies/recommended2.html')


@login_required
@require_GET
def mvti(request):
    answer = request.GET.get('answer')
    movies = ''
    if answer == '1':
        movies = Movie.objects.filter(release_date__year__lte=1999).order_by('?')[:10]
    elif answer == '2':
        movies = Movie.objects.order_by('-vote_average')[:10]
    elif answer == '3':
        movies = Movie.objects.order_by('popularity')[:10]
    else:
        movies = Movie.objects.order_by('?')[:10]

    movies_list = []
    for movie in movies:
        movies_list.append({
            'title': movie.title,
            'release_date': movie.release_date,
            'vote_average': movie.vote_average,
            'poster_path': movie.poster_path,
            })
    response = {
        'moviesList': movies_list,
    }
    return JsonResponse(response)
    

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ movie.title }}</h1>
  <p>
    {% for genre in movie.genres.all %}
    <span>{{ genre.name }}</span>
    {% endfor %}
  </p>
  <p>popularity : {{ movie.popularity }}</p>
  <p>vote average : {{ movie.vote_average }}</p>
  <p>overview : {{ movie.overview }}</p>
  <img src="{{ movie.poster_path }}" alt="">

{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Movies</h1>
  {% for movie in movies %}
    <h3>{{ movie.title }}</h3>
    <p>
      {% for genre in movie.genres.all %}
        <span>{{ genre.name }}</span>
      {% endfor %}
    </p>
    {% if movie.overview %}
      <p>{{ movie.overview|truncatechars:60 }}</p>
    {% else %}
      <p>줄거리 없음</p>
    {% endif %}
    <a href="{% url 'movies:detail' movie.pk %}">[detail]</a>
    <hr>
  {% endfor %}
  
{% endblock %}

movies/templates/movies/recommended.html
{% extends 'base.html' %}

{% block content %}


<h1 class="text-center my-5 fw-bold">{{ today_month }}월에 개봉한 영화들 😎</h1>
<div class="card-group row row-cols-4 g-4">
  {% for movie in movies %}
    <div class="col">
      <div class="card">
        <img src="{{ movie.poster_path }}" class="card-img-top" alt="{{ movie.title }}_poster">
        <div class="card-body">
          <h5 class="card-title text-center fw-bold">{{ movie.title }}</h5>
          <p class="card-text">⭐평점 {{ movie.vote_average }}</p>
          <p class="card-text">
            {% for k, v in from_now.items %}
              {% if k == movie.pk %}
                {% if v == 0 %}
                  이번 달에 개봉한 따끈따끈한 영화!
                {% elif v == 1 %}
                  작년 {{ today_month }}월에 개봉했어요!
                {% elif v == 2 %}
                  재작년 {{ today_month }}월에 개봉했어요!
                {% else %}
                  {{ v }}년 전 {{ today_month }}월에 개봉했어요!
                {% endif %}
              {% endif %}
            {% endfor %}
          </p>
          <a class="text-decoration-none" href="{% url 'movies:detail' movie.pk %}"><p class="card-text"><small class="text-muted">영화상세정보</small></p></a>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

movies/templates/movies/recommended2.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center fw-bold my-4">MBTI 말고 MVTI! 📽<br>{{ request.user }}님의 영화보는 유형은?</h1>
  <div class="text-center">
    <button id="classic" class="btn btn-outline-dark">Oldies but goodies! 클래식이 최고 🎹</button>
    <button id="top100" class="btn btn-outline-dark">대중의 취향이 곧 내 취향 인기 TOP10 🏆</button>
    <br>
    <button id="hipster" class="btn btn-outline-dark">힙스터 기질 발동! 인기 없는 영화만 골라보기 😎</button>
    <button id="random" class="btn btn-outline-dark">우연을 믿어요 랜덤추천 🎲</button>
  </div>
  <div id="card-group" class="card-group row row-cols-5 g-4">
    
</div>

  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const classicBtn = document.querySelector('#classic')
    const top100Btn = document.querySelector('#top100')
    const hipsterBtn = document.querySelector('#hipster')
    const randomBtn = document.querySelector('#random')

    classicBtn.addEventListener('click', function (event) {
      axios({
        method: 'get',
        url: 'http://127.0.0.1:8000/movies/mvti/',
        params: {
          answer: '1'
        }
      })
      .then(function (res) {
        const movieList = res.data.moviesList

        movieList.forEach((movie) => {
          const movieTitle = movie.title
          const movieDate = movie.release_date
          const voteAvg = movie.vote_average
          const posterPath = movie.poster_path

          const div1 = document.createElement('div')
          div1.setAttribute('class', 'col')
          const div2 = document.createElement('div')
          div2.setAttribute('class', 'card')
          const img = document.createElement('img')
          img.setAttribute('src', posterPath)
          img.setAttribute('class', 'card-img-top')
          const div3 = document.createElement('div')
          div3.setAttribute('class', 'card-body')
          const cardTitle = document.createElement('h6')
          cardTitle.setAttribute('class', 'card-title text-center fw-bold')
          cardTitle.innerText = movieTitle
          const cardText = document.createElement('p')
          cardText.setAttribute('class', 'card-text text-center')
          cardText.innerText = `평점 ⭐ ${voteAvg}`
          
          const parentDiv = document.querySelector('#card-group')
          parentDiv.appendChild(div1)
          div1.appendChild(div2)
          div2.append(img, div3)
          div3.append(cardTitle)
          div3.append(cardText) 
        })
      })
    }, {once: true})

    top100Btn.addEventListener('click', function (event) {
      axios({
        method: 'get',
        url: 'http://127.0.0.1:8000/movies/mvti/',
        params: {
          answer: '2'
        }
      })
      .then(function (res) {
        const movieList = res.data.moviesList

        movieList.forEach((movie) => {
          const movieTitle = movie.title
          const movieDate = movie.release_date
          const voteAvg = movie.vote_average
          const posterPath = movie.poster_path

          const div1 = document.createElement('div')
          div1.setAttribute('class', 'col')
          const div2 = document.createElement('div')
          div2.setAttribute('class', 'card')
          const img = document.createElement('img')
          img.setAttribute('src', posterPath)
          img.setAttribute('class', 'card-img-top')
          const div3 = document.createElement('div')
          div3.setAttribute('class', 'card-body')
          const cardTitle = document.createElement('h6')
          cardTitle.setAttribute('class', 'card-title text-center fw-bold')
          cardTitle.innerText = movieTitle
          const cardText = document.createElement('p')
          cardText.setAttribute('class', 'card-text text-center')
          cardText.innerText = `평점 ⭐ ${voteAvg}`
          
          const parentDiv = document.querySelector('#card-group')
          parentDiv.appendChild(div1)
          div1.appendChild(div2)
          div2.append(img, div3)
          div3.append(cardTitle)
          div3.append(cardText) 
        })
      })
    }, {once: true})

    hipsterBtn.addEventListener('click', function (event) {
      axios({
        method: 'get',
        url: 'http://127.0.0.1:8000/movies/mvti/',
        params: {
          answer: '3'
        }
      })
      .then(function (res) {
        const movieList = res.data.moviesList

        movieList.forEach((movie) => {
          const movieTitle = movie.title
          const movieDate = movie.release_date
          const voteAvg = movie.vote_average
          const posterPath = movie.poster_path

          const div1 = document.createElement('div')
          div1.setAttribute('class', 'col')
          const div2 = document.createElement('div')
          div2.setAttribute('class', 'card')
          const img = document.createElement('img')
          img.setAttribute('src', posterPath)
          img.setAttribute('class', 'card-img-top')
          const div3 = document.createElement('div')
          div3.setAttribute('class', 'card-body')
          const cardTitle = document.createElement('h6')
          cardTitle.setAttribute('class', 'card-title text-center fw-bold')
          cardTitle.innerText = movieTitle
          const cardText = document.createElement('p')
          cardText.setAttribute('class', 'card-text text-center')
          cardText.innerText = `평점 ⭐ ${voteAvg}`
          
          const parentDiv = document.querySelector('#card-group')
          parentDiv.appendChild(div1)
          div1.appendChild(div2)
          div2.append(img, div3)
          div3.append(cardTitle)
          div3.append(cardText) 
        })
      })
    }, {once: true})

    randomBtn.addEventListener('click', function (event) {
      axios({
        method: 'get',
        url: 'http://127.0.0.1:8000/movies/mvti/',
        params: {
          answer: '4'
        }
      })
      .then(function (res) {
        const movieList = res.data.moviesList

        movieList.forEach((movie) => {
          const movieTitle = movie.title
          const movieDate = movie.release_date
          const voteAvg = movie.vote_average
          const posterPath = movie.poster_path

          const div1 = document.createElement('div')
          div1.setAttribute('class', 'col')
          const div2 = document.createElement('div')
          div2.setAttribute('class', 'card')
          const img = document.createElement('img')
          img.setAttribute('src', posterPath)
          img.setAttribute('class', 'card-img-top')
          const div3 = document.createElement('div')
          div3.setAttribute('class', 'card-body')
          const cardTitle = document.createElement('h6')
          cardTitle.setAttribute('class', 'card-title text-center fw-bold')
          cardTitle.innerText = movieTitle
          const cardText = document.createElement('p')
          cardText.setAttribute('class', 'card-text text-center')
          cardText.innerText = `평점 ⭐ ${voteAvg}`
          
          const parentDiv = document.querySelector('#card-group')
          parentDiv.appendChild(div1)
          div1.appendChild(div2)
          div2.append(img, div3)
          div3.append(cardTitle)
          div3.append(cardText) 
        })
      })
    }, {once: true})
  </script>
{% endblock %}