accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('follow/<int:user_pk>/', views.follow, name='follow'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/comments/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

pjt09/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/dacf7dcd9c.js" crossorigin="anonymous"></script>
  <title>Document</title>
</head>
<body>
  {% include 'nav.html' %}
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand pe-3 title-font" href="{% url 'community:index' %}">REVIEWER</a>
    <div class="collapse navbar-collapse d-flex justify-content-between text-white" id="navbarSupportedContent">
      <a class="active text-decoration-none text-white" aria-current="page" href="{% url 'community:create' %}"><i class="fas fa-plus"></i></a>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
          {% if request.user.is_authenticated %}
            <span class="me-3 content-font">환영합니다, {{ request.user }}님!</span>
            <a href="{% url 'accounts:profile' request.user.username %}" class="active btn btn-success content-font">내 프로필</a>
            <form action="{% url 'accounts:logout' %}" method="POST" class="d-inline">
              {% csrf_token %}
              <input type="submit" value="로그아웃" class="btn btn-secondary content-font">
            </form>
          {% else %}
            <span class="me-3 content-font">환영합니다, 손님!</span>
            <a class="active btn btn-primary content-font" aria-current="page" href="{% url 'accounts:login' %}">로그인</a>
            <a class="active btn btn-light content-font" aria-current="page" href="{% url 'accounts:signup' %}">회원가입</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>